// Code generated by "stringer -type=FrameChannelMode"; DO NOT EDIT

package mp3

import "fmt"

const _FrameChannelMode_name = "StereoJointStereoDualChannelSingleChannelChannelModeMax"

var _FrameChannelMode_index = [...]uint8{0, 6, 17, 28, 41, 55}

func (i FrameChannelMode) String() string {
	if i >= FrameChannelMode(len(_FrameChannelMode_index)-1) {
		return fmt.Sprintf("FrameChannelMode(%d)", i)
	}
	return _FrameChannelMode_name[_FrameChannelMode_index[i]:_FrameChannelMode_index[i+1]]
}
