// generated by stringer -type=FrameVersion; DO NOT EDIT

package mp3

import "fmt"

const _FrameVersion_name = "MPEG25MPEGReservedMPEG2MPEG1"

var _FrameVersion_index = [...]uint8{6, 18, 23, 28}

func (i FrameVersion) String() string {
	if i >= FrameVersion(len(_FrameVersion_index)) {
		return fmt.Sprintf("FrameVersion(%d)", i)
	}
	hi := _FrameVersion_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _FrameVersion_index[i-1]
	}
	return _FrameVersion_name[lo:hi]
}
