// generated by stringer -type=FrameLayer; DO NOT EDIT

package mp3

import "fmt"

const _FrameLayer_name = "LayerReservedLayer3Layer2Layer1"

var _FrameLayer_index = [...]uint8{13, 19, 25, 31}

func (i FrameLayer) String() string {
	if i >= FrameLayer(len(_FrameLayer_index)) {
		return fmt.Sprintf("FrameLayer(%d)", i)
	}
	hi := _FrameLayer_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _FrameLayer_index[i-1]
	}
	return _FrameLayer_name[lo:hi]
}
