// generated by stringer -type=FrameEmphasis; DO NOT EDIT

package mp3

import "fmt"

const _FrameEmphasis_name = "EmphNoneEmph5015EmphReservedEmphCCITJ17"

var _FrameEmphasis_index = [...]uint8{8, 16, 28, 39}

func (i FrameEmphasis) String() string {
	if i >= FrameEmphasis(len(_FrameEmphasis_index)) {
		return fmt.Sprintf("FrameEmphasis(%d)", i)
	}
	hi := _FrameEmphasis_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _FrameEmphasis_index[i-1]
	}
	return _FrameEmphasis_name[lo:hi]
}
