// Code generated by "stringer -type=FrameVersion"; DO NOT EDIT

package mp3

import "fmt"

const _FrameVersion_name = "MPEG25MPEGReservedMPEG2MPEG1VERSIONMAX"

var _FrameVersion_index = [...]uint8{0, 6, 18, 23, 28, 38}

func (i FrameVersion) String() string {
	if i >= FrameVersion(len(_FrameVersion_index)-1) {
		return fmt.Sprintf("FrameVersion(%d)", i)
	}
	return _FrameVersion_name[_FrameVersion_index[i]:_FrameVersion_index[i+1]]
}
