// Code generated by "stringer -type=FrameLayer"; DO NOT EDIT

package mp3

import "fmt"

const _FrameLayer_name = "LayerReservedLayer3Layer2Layer1LayerMax"

var _FrameLayer_index = [...]uint8{0, 13, 19, 25, 31, 39}

func (i FrameLayer) String() string {
	if i >= FrameLayer(len(_FrameLayer_index)-1) {
		return fmt.Sprintf("FrameLayer(%d)", i)
	}
	return _FrameLayer_name[_FrameLayer_index[i]:_FrameLayer_index[i+1]]
}
